<h1>add vote sys</h1>
<form action="./additem" method="post">
<table>
<tr><td>name</td><td><input type="text" name="name"/></td></tr>
<tr><td>description</td>
<td>
<textarea cols="30" rows="5" name="description"></textarea>
</td>
</tr>
<tr><td>init</td><td><input type="text" name="vote_count"/></td></tr>
<tr><td><input type="submit" value="submit" /></td><td><input type="reset" value="reset" /></td></tr>
</table>
</form>